/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as guestRouteRouteImport } from './routes/(guest)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as guestSignupRouteImport } from './routes/(guest)/signup'
import { Route as guestLoginRouteImport } from './routes/(guest)/login'

const guestRouteRoute = guestRouteRouteImport.update({
  id: '/(guest)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const guestSignupRoute = guestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => guestRouteRoute,
} as any)
const guestLoginRoute = guestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => guestRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof guestLoginRoute
  '/signup': typeof guestSignupRoute
}
export interface FileRoutesByTo {
  '/login': typeof guestLoginRoute
  '/signup': typeof guestSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRoute
  '/(guest)': typeof guestRouteRouteWithChildren
  '/(guest)/login': typeof guestLoginRoute
  '/(guest)/signup': typeof guestSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/signup'
  id: '__root__' | '/(app)' | '/(guest)' | '/(guest)/login' | '/(guest)/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRoute
  guestRouteRoute: typeof guestRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(guest)': {
      id: '/(guest)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof guestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guest)/signup': {
      id: '/(guest)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof guestSignupRouteImport
      parentRoute: typeof guestRouteRoute
    }
    '/(guest)/login': {
      id: '/(guest)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof guestLoginRouteImport
      parentRoute: typeof guestRouteRoute
    }
  }
}

interface guestRouteRouteChildren {
  guestLoginRoute: typeof guestLoginRoute
  guestSignupRoute: typeof guestSignupRoute
}

const guestRouteRouteChildren: guestRouteRouteChildren = {
  guestLoginRoute: guestLoginRoute,
  guestSignupRoute: guestSignupRoute,
}

const guestRouteRouteWithChildren = guestRouteRoute._addFileChildren(
  guestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRoute,
  guestRouteRoute: guestRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
